# Generated by Django 4.2 on 2023-04-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('doctor_ID', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_Name', models.CharField(max_length=50)),
                ('doctor_Email', models.CharField(max_length=50)),
                ('doctor_Contact', models.CharField(max_length=20)),
                ('doctor_Address', models.TextField()),
                ('doctor_Avatar', models.ImageField(upload_to='images')),
            ],
        ),
    ]
