# Generated by Django 4.2 on 2023-04-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_Department',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
