# Generated by Django 4.2 on 2023-04-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_Position',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
